### ISSUE TITLE
existing alternatives?

### ISSUE THREAD

**Issue by vitaly-t** [reaktor/pg-using-bluebird#1]
Have you tried using [pg-promise](https://github.com/vitaly-t/pg-promise)? It does well what you are trying to implement here, and much more.

**Comment by hvrauhal** [comment]
I have not tried using it.

For my current project we did a review of the available libraries for promisifying node-postgres in October of 2014. As nothing on npm seemed to offer transactions that used the [resource-management functionality of bluebird](https://github.com/petkaantonov/bluebird/blob/master/API.md#resource-management), we ended up refining the examples from bluebird documentation and have been using them happily ever since.

Then, half a year later, we finally pulled the promisifying postgres code apart from the rest of the codebase and published it as as this project.

The intention is to one day split the sql generating parts from the promisifying parts into their own project so that the pg-using-bluebird codebase will be even smaller and more focused.

**Comment by vitaly-t** [comment]
I did the same research back in December 2014, and nothing usable came up, that's why I wrote my own library, which also started as part of an ongoing project and then later on was separated into its own library, much like most of stuff published here on Git :)

**Comment by hvrauhal** [comment]
:). Hopefully this issue and discussion will be helpful for future developers looking for ways to promisify postgres. I see use for both of these modules, pg-promise being a more generic solution, pg-using-bluebird being bluebird-only minimalistic approach.
